@extends('layouts.app')
@section('content')
    @switch($dm['type_user'])
        @case(1)
                <deposit-component></deposit-component>
        @break
        @case(2)
                <deposit-component></deposit-component>
        @break
        @case(3)
                <deposit-component></deposit-component>
        @break
        @case(4)
                <deposit-component></deposit-component>
        @break
        @default
                <deposit-component></deposit-component>
    @endswitch
        
@endsection
